\input texinfo
@c @setfilename emacs-web-server.info
@documentencoding utf-8
@settitle Emacs Web Server (ews) User Manual

@copying
This file documents the Emacs Web Server (ews)

Copyright (C) 2013 Eric Schulte <schulte.eric@@gmail.com>

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with the Invariant Section being ``GNU GENERAL PUBLIC LICENSE,''
A copy of the license is included in the section entitled
``GNU Free Documentation License.''
@end quotation
@end copying

@dircategory Emacs misc features
@direntry
* Emacs Web Server: (ews).      Web Server for Emacs.
@end direntry

@titlepage
@title Emacs Web Server (ews) User Manual
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of the contents at the beginning.
@contents

@ifnottex
@node Top, Introduction, (dir), (dir)
@top Emacs Web Server User Manual

@insertcopying
@end ifnottex

@menu
* Introduction::                Getting to know the Emacs Web Server
* Handlers::                    Handlers respond to HTTP requests
* Request Headers::             Getting information on HTTP requests
* Usage Examples::              Examples demonstrating usage
* Function Index::              List of Functions

Appendices

* Copying::                     The GNU General Public License gives
                                you permission to redistribute GNU Emacs on
                                certain terms; it also explains that there is
                                no warranty.
* GNU Free Documentation License::  The license for this documentation.
* Index::                       Complete index.




@end menu

@node Introduction, Handlers, Top, Top
@chapter Introduction
@cindex introduction

The Emacs Web Server is a Web server implemented in Emacs Lisp using
Emacs network communication primitives.  HTTP requests are matched to
handlers (@pxref{Handlers}) which are implemented as Emacs Lisp
functions.  Handler functions receive the HTTP connection process and
a request object (@pxref{Request Headers}) which holds information
about the request.  Handlers write responses directly to the
connection process.

A number of examples (@pxref{Usage Examples}) demonstrate usage of the
Emacs Web Server, as well as a complete list of the functions defining
the interface (@pxref{Function Index}).

@node Handlers, Request Headers, Handlers, Top
@chapter Handlers
@cindex handlers

A handler looks like this and does this.

@node Request Headers, Usage Examples, Handlers, Top
@chapter Request Headers
@cindex request headers

Information on requests is stored in a @code{request} object.  This object is
used to decide which handler to call, and is passed to the called handler.
Request objects hold information such as the type of request (@code{GET},
@code{POST}, etc.), the path of the request, and any parameter information
encoded in the request URL as form data.

The request is received as a string which is parsed into an alist.
This parsing is only performed as needed by a handler or as necessary
to select a handler to call.  HTML Headers are keyed using uppercase
keywords (e.g., @code{:GET}), and user supplied parameters are keyed
using the string name of the parameter.  The following functions may
be used to read request alists and cause any needed parsing to take
place as a side effect.

@defun ews-get item request
@code{ews-get} returns the value associated with @code{item} in
@code{request}.  Any pending parsing of the @code{request} is
performed until @code{item} is found.

@example
(ews-get :GET request)
    @result{} "/"
    ;; Effect: Only the first line of the request is parsed.
(ews-get "foo" request)
    @result{} "bar"
    ;; Effect: Parameters are parsed until one named "foo" is
    ;;         found or no more parameters are left.
@end example
@end defun

@node Usage Examples, Hello World, Request Headers, Top
@chapter Usage Examples
@cindex usage examples

These examples demonstrate usage.
@menu
* Hello World::                 Serve ``Hello World'' to every request
* Hello World UTF8::            Serve ``Hello World'' w/UTF8 encoding
* Hello World HTML::            Serve ``Hello World'' in HTML
* File Server::                 Serve files from a document root
* URL Parameter Echo::          Echo Parameters from a URL query string
* POST Echo::                   Echo POST parameters back
@end menu

@node Hello World, Hello World UTF8, Usage Examples, Usage Examples
@section Hello World
@verbatiminclude ../examples/0-hello-world.el

@node Hello World UTF8, Hello World HTML, Hello World, Usage Examples
@section Hello World UTF8
@verbatiminclude ../examples/1-hello-world-utf8.el

@node Hello World HTML, File Server, Hello World UTF8, Usage Examples
@section Hello World HTML
@verbatiminclude ../examples/2-hello-world-html.el

@node File Server, URL Parameter Echo, Hello World HTML, Usage Examples
@section File Server
@verbatiminclude ../examples/3-file-server.el

@node URL Parameter Echo, POST Echo, File Server, Usage Examples
@section URL Parameter Echo
@verbatiminclude ../examples/4-url-param-echo.el

@node POST Echo, Function Index, URL Parameter Echo, Usage Examples
@section POST Echo
POST parameters are used for example when HTML forms are submitted.

@verbatiminclude ../examples/5-post-echo.el

@node Function Index, Copying, Usage Examples, Top
@chapter Function Index
@cindex function index

These are the main functions one would use.

@node Copying, GNU Free Documentation License, Function Index, Top
@appendix GNU GENERAL PUBLIC LICENSE
@include gpl.texi

@node GNU Free Documentation License, Index, Copying, Top
@appendix GNU Free Documentation License
@include doclicense.texi

@node Index,  , GNU Free Documentation License, Top
@unnumbered Index

@printindex cp

@bye
